import { toRoman } from './index';
import { strictEqual } from "assert";

describe(('Conversión a números romanos'), () => {
  it('test 1', () => { strictEqual(toRoman(1), "I") })
  it('test 2', () => { strictEqual(toRoman(2), "II") })
  it('test 3', () => { strictEqual(toRoman(3), "III") })
  it('test 4', () => { strictEqual(toRoman(4), "IV") })
  it('test 5', () => { strictEqual(toRoman(5), "V") })
  it('test 7', () => { strictEqual(toRoman(7), "VII") })
  it('test 9', () => { strictEqual(toRoman(9), "IX") })
  it('test 12', () => { strictEqual(toRoman(12), "XII") })
  it('test 16', () => { strictEqual(toRoman(16), "XVI") })
  it('test 14', () => { strictEqual(toRoman(14), "XIV") })
  it('test 18', () => { strictEqual(toRoman(18), "XVIII") })
  it('test 20', () => { strictEqual(toRoman(20), "XX") })
  it('test 19', () => { strictEqual(toRoman(19), "XIX") })
  it('test 30', () => { strictEqual(toRoman(30), "XXX") })
  it('test 35', () => { strictEqual(toRoman(35), "XXXV") })
  it('test 40', () => { strictEqual(toRoman(40), "XL") })
  it('test 44', () => { strictEqual(toRoman(44), "XLIV") })
  it('test 64', () => { strictEqual(toRoman(64), "LXIV") })
  it('test 49', () => { strictEqual(toRoman(49), "XLIX") })
  it('test 90', () => { strictEqual(toRoman(90), "XC") })
  it('test 269', () => { strictEqual(toRoman(269), "CCLXIX") })
  it('test 3999', () => { strictEqual(toRoman(3999), "MMMCMXCIX") })
  it('test 3458', () => { strictEqual(toRoman(3458), "MMMCDLVIII") })
})